package com.sample
 
import com.sample.DroolsTest.Message;
//Creen al menos 10 reglas en Drools...
//de las cuales se implementen las dos de la figura 9 del artículo.


//Una sola declaración
//En vez de tener que declarar por cada tipo de sensor
//declare Sensor
	//nombre: String @key
	//Que HVAC/Climatiazacion analiza
	//tipoClimatizacion: TipoHVAC @key
	//Teoricamente sensores siempre encendidos...
	//Pero puede haber algún caso inesperado
	//encendido: boolean @key
	//presenciaDetectada: boolean @key
//end

//Cambio sensor por persona
//horas\precencia de 0 a 24
declare Persona
	nombre: String @key
	presencia: boolean @key
	quiereEncender: boolean @key
	//presenciaInicio: int @key
	//presenciaFin: int @key 
end

declare FuenteGasto
	//nombre: String @key
	encendidoTotal: boolean @key
	encendidoParcial: boolean @key
	tipoHvac: TipoHVAC @key
end

declare TipoHVAC
	HVAC: String @key
end

declare FuenteNatural
	//Aportacion puede ser luz, calefaccion, otro
	hvac: TipoHVAC @key
	//nombre: String @key
	presenciaTotal: boolean @key
	presenciaParcial: boolean @key
	//horaInicio: int @key
	//horaFin: int @key
end

//Momentos en que las dos aportaciones existen
declare NaturalArtificial
	hvac: TipoHVAC @key
	mayorUmbral: boolean @key
end

//Tsp=set point temperature, trec=recovery time
//Iluminación como electricidad
rule "Carga hechos"
	then
		TipoHVAC ac = new TipoHVAC("AC");
		insert(ac);
		TipoHVAC calef = new TipoHVAC("Calefacción");
		insert(calef);
		TipoHVAC ilum = new TipoHVAC("Iluminación");
		insert(ilum);
		
		//Por el momento dejaré uno de cada clase
		//insert(new FuenteGastoEnergetico("ACuno",false,ac));
		//insert(new FuenteGastoEnergetico("Calentador",false,calef));
		//insert(new FuenteGastoEnergetico("Focos",false,ilum));
		insert(new FuenteGasto(false,false,ac));
		insert(new FuenteGasto(false,false,calef));
		insert(new FuenteGasto(false,false,ilum));
		
		insert(new Persona("Emilino",true,true));
		
		//insert(new FuenteNatural(ilum,"LuzNatural",true));
		//insert(new FuenteNatural(calef,"Sol",true));
		//insert(new FuenteNatural(ac,"Ventana abierta",true));
		insert(new FuenteNatural(ilum,true,false));
		insert(new FuenteNatural(calef,true,false));
		insert(new FuenteNatural(ac,true,false));
		
		insert(new NaturalArtificial(ilum,false));
end

rule "Encender luces"
	when
		$persona: Persona(quiereEncender == true)
		$fuenteIlum: FuenteGasto(encendidoTotal==false && tipoHvac=="Iluminación")
	then
		$fuenteIlum.setEncendido(true);
end

rule "Hay luz de día suficiente"
	when
		$ilum: FuenteNatural(hvac=="Iluminación" && presenciaTotal==true)
		$fuenteIlum: FuenteGasto(encendidoTotal==true && tipoHvac=="Iluminación")
	then
		$fuenteIlum.setEncendidoTotal(false);
		$fuenteIlum.setEncendidoParcial(false);
end
rule "No hay luz de día suficiente"
	when
		$ilum: FuenteNatural(hvac=="Iluminación" && presenciaTotal==false && presenciaParcial==true)
		$fuenteIlum: FuenteGasto(encendidoTotal==true && tipoHvac=="Iluminación")
	then
		$fuenteIlum.setEncendidoTotal(false);
		$fuenteIlum.setEncendidoParcial(true);
end

rule "No hay luz de día"
	when
		$ilum: FuenteNatural(hvac=="Iluminación" &&presenciaTotal==false &&presenciaParcial==false)
		$fuenteIlum: FuenteGasto(tipoHvac=="Iluminación")
	then
		$fuenteIlum.setEncendidoParcial(false);
		$fuenteIlum.setEncendidoTotal(true);
end

rule "Luz natural y artificial superan el umbral"
	when
		$ilum: FuenteNatural(hvac=="Iluminación" && (presenciaTotal==true || presenciaParcial==true))
		$fuenteIlum: FuenteGasto(tipoHvac=="Iluminación"&&(encendidoTotal==true||encendidoParcial==true))
		$juntos: NaturalArtificial(hvac=="Iluminación")
	then
		$juntos.setMayorUmbral(true);
		$fuenteIlum.setEncendidoTotal(false);
		$fuenteIlum.setEncendidoParcial(true);
end

rule "Luz natural y artificial no superan el umbral"
	when
		$ilum: FuenteNatural(hvac=="Iluminación" && presenciaTotal==false && presenciaParcial==false)
		$fuenteIlum: FuenteGasto(tipoHvac=="Iluminación"&&(encendidoTotal==true||encendidoParcial==true))
		$juntos: NaturalArtificial(hvac=="Iluminación")
	then
		$juntos.setMayorUmbral(false);
		$fuenteIlum.setEncendidoTotal(true);
		$fuenteIlum.setEncendidoParcial(false);
end

rule "Persona No Apagar luces"
	when
		$pers: Persona(presencia==true && quiereEncender==true)
		$fuenteIlum: FuenteGasto(tipoHvac=="Iluminación"&&(encendidoTotal==true||encendidoParcial==true))
	then
		$fuenteIlum.setEncendidoTotal(true);
		$fuenteIlum.setEncendidoParcial(false);
end

rule "Persona Apagar luces"
	when
		$pers: Persona(presencia==true && quiereEncender==false)
		$fuenteIlum: FuenteGasto(tipoHvac=="Iluminación"&&(encendidoTotal==true||encendidoParcial==true))
	then
		$fuenteIlum.setEncendidoTotal(false);
		$fuenteIlum.setEncendidoParcial(false);
end

rule "Apagar luces No hay nadie"
	when
		$pers: Persona(presencia==false)
		$fuenteIlum: FuenteGasto(tipoHvac=="Iluminación"&&(encendidoTotal==true||encendidoParcial==true))
	then
		$fuenteIlum.setEncendidoTotal(false);
		$fuenteIlum.setEncendidoParcial(false);
end

rule "Acaba de llegar"
	when
		$pers: Persona(presencia==false)
	then
		$pers.getPresencia(true);
end

rule "Ya se va"
	when
		$pers: Persona(presencia==true)
	then
		$pers.setPresencia(false);
end

rule "Quiere encender"
	when
		$pers: Persona(quiereEncender==false)
	then
		$pers.setQuiereEncender(true);
end

rule "No quiere encender"
	when
		$pers: Persona(quiereEncender==true)
	then
		$pers.setQuiereEncender(false);
end

//AC es aire acondicionado
rule "AC"
	when
	then
end
rule "Calefaccion"
	when
	then
end