package org.drools.workshop;
import org.drools.workshop.model.*;

rule "Creacion de Habitaciones"
     when
     then
      insert(new Habitacion(1,"Sala",1,false));
      System.out.println("Hechos Creados");
end

rule "Creacion de Sensores"
    when
    then
      insert(new Sensor(1,"Sensor de Temperatura",1,0));
      insert(new Sensor(2,"Sensor de Ocupacion",1,0));
      insert(new Sensor(3,"Sensor de Humedad",1,0));
      insert(new Sensor(4,"Sensor de Temperatura",2,0));
      insert(new Sensor(5,"Sensor de Ocupacion",2,0));
      insert(new Sensor(6,"Sensor de Humedad",2,0));
      System.out.println("Hechos Creados");
end

rule "Creacion de Dispositivos"
    when
    then
      insert(new Dispositivo(1,"Aire Acondicionado",false,"",0,1));
      insert(new Dispositivo(2,"Luces",false,"",0,1));
      insert(new Dispositivo(3,"Deshumidificador",false,"",0,1));
      insert(new Dispositivo(4,"Aire Acondicionado",false,"",0,2));
      insert(new Dispositivo(5,"Luces",false,"",0,2));
      insert(new Dispositivo(6,"Deshumidificador",false,"",0,2));
end

rule "Actualizacion de Mediciones Actuales"
    when
      $m : Medicion()
      $s : Sensor($m.getIdForaneoSensor() == idSensor && $m.getIdMedicion() > idMedicionActual)
    then
      $s.setIdMedicionActual($m.getIdMedicion());
end


/*
**************************************************************
REGLAS PARA LA TEMPERATURA
**************************************************************
*/

rule "Cuando la temperatura es mayor o igual a 40°"
    when
      $s : Sensor(nombreSensor == "Sensor de Temperatura")
      $m : Medicion($s.getIdSensor() == idForaneoSensor && valor >= 40)
      $d : Dispositivo($s.getIdForaneoHabitacion() == idForaneoHabitacion && nombreDispositivo == "Aire Acondicionado")
    then
      $d.setEstado(true);
      $d.setModo("frio");
      $d.setIntensidad(3);
end

rule "Cuando la temperatura es mayor a 35 y a 40"
    when
      $s : Sensor(nombreSensor == "Sensor de Temperatura")
      $m : Medicion($s.getIdSensor() == idForaneoSensor && valor > 35 && valor < 40)
      $d : Dispositivo($s.getIdForaneoHabitacion() == idForaneoHabitacion && nombreDispositivo == "Aire Acondicionado")
    then
      $d.setEstado(true);
      $d.setModo("frio");
      $d.setIntensidad(2);
end

rule "Cuando la temperatura es mayor a 27 y menor o igual a 35°"
    when
      $s : Sensor(nombreSensor == "Sensor de Temperatura")
      $m : Medicion($s.getIdSensor() == idForaneoSensor && valor > 27 && valor <= 35)
      $d : Dispositivo($s.getIdForaneoHabitacion() == idForaneoHabitacion && nombreDispositivo == "Aire Acondicionado")
    then
      $d.setEstado(true);
      $d.setModo("frio");
      $d.setIntensidad(1);
end

rule "Cuando la temperatura es menor o igual a 5"
    when
      $s : Sensor(nombreSensor == "Sensor de Temperatura")
      $m : Medicion($s.getIdSensor() == idForaneoSensor && valor <= 5)
      $d : Dispositivo($s.getIdForaneoHabitacion() == idForaneoHabitacion && nombreDispositivo == "Aire Acondicionado")
    then
      $d.setEstado(true);
      $d.setModo("caliente");
      $d.setIntensidad(3);
end

rule "Cuando la temperatura es mayor a 5 pero menor o igual a 13"
    when
      $s : Sensor(nombreSensor == "Sensor de Temperatura")
      $m : Medicion($s.getIdSensor() == idForaneoSensor && valor > 5 && valor <= 13)
      $d : Dispositivo($s.getIdForaneoHabitacion() == idForaneoHabitacion && nombreDispositivo == "Aire Acondicionado")
    then
      $d.setEstado(true);
      $d.setModo("caliente");
      $d.setIntensidad(2);
end

rule "Cuando la temperatura es mayor a 13 pero menor o igual a 20"
    when
      $s : Sensor(nombreSensor == "Sensor de Temperatura")
      $m : Medicion($s.getIdSensor() == idForaneoSensor && valor > 13 && valor <= 20)
      $d : Dispositivo($s.getIdForaneoHabitacion() == idForaneoHabitacion && nombreDispositivo == "Aire Acondicionado")
    then
      $d.setEstado(true);
      $d.setModo("caliente");
      $d.setIntensidad(1);
end

rule "Cuando la temperatura es mayor a 20 pero menor o igual a 27"
    when
      $s : Sensor(nombreSensor == "Sensor de Temperatura")
      $m : Medicion($s.getIdSensor() == idForaneoSensor && valor > 20 && valor <= 27)
      $d : Dispositivo($s.getIdForaneoHabitacion() == idForaneoHabitacion && nombreDispositivo == "Aire Acondicionado")
    then
      $d.setEstado(false);
      $d.setModo("");
      $d.setIntensidad(0);
end

/*
**************************************************************
REGLAS PARA LA ILUMINACION
**************************************************************
*/

rule "Cuando la habitacion esta vacia"
    when
      $s : Sensor(nombreSensor == "Sensor de Ocupacion")
      $m : Medicion($s.getIdSensor() == idForaneoSensor && valor == 0)
      $d : Dispositivo($s.getIdForaneoHabitacion() == idForaneoHabitacion && nombreDispositivo == "Luces")
    then
      $d.setEstado(false);
      $d.setModo("");
      $d.setIntensidad(0);
end

rule "Cuando hay alguien en la habitacion y no hay ventanas"
    when
      $s : Sensor(nombreSensor == "Sensor de Ocupacion")
      $h : Habitacion($s.getIdForaneoHabitacion() == idHabitacion)
      $m : Medicion($s.getIdSensor() == idForaneoSensor && valor > 0 && $h.getVentana() == false)
      $d : Dispositivo($s.getIdForaneoHabitacion() == idForaneoHabitacion && nombreDispositivo == "Luces")
    then
      $d.setEstado(true);
      $d.setModo("calido");
      $d.setIntensidad(10);
end

rule "Cuando hay alguien en la habitacion, hay ventanas, y la hora esta de 9AM a 17PM"
    when
      $s : Sensor(nombreSensor == "Sensor de Ocupacion")
      $h : Habitacion($s.getIdForaneoHabitacion() == idHabitacion)
      $m : Medicion($s.getIdSensor() == idForaneoSensor && valor > 0 && $h.getVentana() == true && hora >= 9 && hora <= 17)
      $d : Dispositivo($s.getIdForaneoHabitacion() == idForaneoHabitacion && nombreDispositivo == "Luces")
    then
      $d.setEstado(true);
      $d.setModo("frio");
      $d.setIntensidad(5);
end

rule "Cuando hay alguien en la habitacion, hay ventanas, y la hora es mas temprana de 9AM"
    when
      $s : Sensor(nombreSensor == "Sensor de Ocupacion")
      $h : Habitacion($s.getIdForaneoHabitacion() == idHabitacion)
      $m : Medicion($s.getIdSensor() == idForaneoSensor && valor > 0 && $h.getVentana() == true && hora < 9)
      $d : Dispositivo($s.getIdForaneoHabitacion() == idForaneoHabitacion && nombreDispositivo == "Luces")
    then
      $d.setEstado(true);
      $d.setModo("calido");
      $d.setIntensidad(9);
end

rule "Cuando hay alguien en la habitacion, hay ventanas, y la hora es mas tarde de 17PM"
    when
      $s : Sensor(nombreSensor == "Sensor de Ocupacion")
      $h : Habitacion($s.getIdForaneoHabitacion() == idHabitacion)
      $m : Medicion($s.getIdSensor() == idForaneoSensor && valor > 0 && $h.getVentana() == true && hora > 17)
      $d : Dispositivo($s.getIdForaneoHabitacion() == idForaneoHabitacion && nombreDispositivo == "Luces")
    then
      $d.setEstado(true);
      $d.setModo("calido");
      $d.setIntensidad(9);
end

/*
**************************************************************
REGLAS PARA LA HUMEDAD
**************************************************************
*/

rule "Cuando la humedad es menor al 30 porciento"
    when
      $s : Sensor(nombreSensor == "Sensor de Humedad")
      $m : Medicion($s.getIdSensor() == idForaneoSensor && valor < 30)
      $d : Dispositivo($s.getIdForaneoHabitacion() == idForaneoHabitacion && nombreDispositivo == "Deshumidificador")
    then
      $d.setEstado(false);
      $d.setModo("");
      $d.setIntensidad(0);
end

rule "Cuando la humedad es mayor o igual a 30 y menor a 45 porciento"
    when
      $s : Sensor(nombreSensor == "Sensor de Humedad")
      $m : Medicion($s.getIdSensor() == idForaneoSensor && valor >= 30 && valor < 45)
      $d : Dispositivo($s.getIdForaneoHabitacion() == idForaneoHabitacion && nombreDispositivo == "Deshumidificador")
    then
      $d.setEstado(true);
      $d.setModo("accionando");
      $d.setIntensidad(1);
end

rule "Cuando la humedad es mayor o igual a 45 y menor a 60 porciento"
    when
      $s : Sensor(nombreSensor == "Sensor de Humedad")
      $m : Medicion($s.getIdSensor() == idForaneoSensor && valor >= 45 && valor < 60)
      $d : Dispositivo($s.getIdForaneoHabitacion() == idForaneoHabitacion && nombreDispositivo == "Deshumidificador")
    then
      $d.setEstado(true);
      $d.setModo("accionando");
      $d.setIntensidad(2);
end

rule "Cuando la humedad es mayor o igual a 60  porciento"
    when
      $s : Sensor(nombreSensor == "Sensor de Humedad")
      $m : Medicion($s.getIdSensor() == idForaneoSensor && valor >= 60)
      $d : Dispositivo($s.getIdForaneoHabitacion() == idForaneoHabitacion && nombreDispositivo == "Deshumidificador")
    then
      $d.setEstado(true);
      $d.setModo("accionando");
      $d.setIntensidad(3);
end
