package org.drools.workshop;
import org.drools.workshop.model.*;


rule "es dispositivo"
    when
        $d: Dispositivo()
    then
        System.out.println($d.getNombreDispositivo());
end

rule "es habitacion"
    when
        $h: Habitacion()
    then
        System.out.println($h.getNombreHabitacion());
end

rule "es medicion"
    when
        $m: Medicion()
    then
        System.out.println($m.getValor());
end



rule "consumo promedio sala"
     when
	$h : Habitacion(nombreHabitacion == "Living Room" )
     then
	insert(new Valor($h,58,4.2));
  insert(new Dispositivo(95,"Lampara","Iluminacion",1));
  insert(new Dispositivo(37,"Calentador","Calefaccion",1));
end

rule "consumo promedio dormitorio"
     when
	$h : Habitacion(nombreHabitacion == "Bedroom" )
     then
	insert(new Valor($h,45,3.1));
end

rule "consumo promedio salon de estudio"
     when
	$h : Habitacion(nombreHabitacion == "Study Room" )
     then
	insert(new Valor($h,27,2.4));
end

rule "consumo promedio comedor"
     when
	$h : Habitacion(nombreHabitacion == "Dinning Room" )
     then
	insert(new Valor($h,28,2.0));
end

rule "imprimir valores"
     when
	     $v : Valor()
     then
	System.out.println($v);
end


rule "consumo promedio cocina"
     when
	    $h : Habitacion(nombreHabitacion == "Kitchen" )
     then
	insert(new Valor($h,18,1.9));
end

rule "consumo promedio baño"
     when
	$h : Habitacion(nombreHabitacion == "Bathroom" )
     then
	insert(new Valor($h,20,1.9));
end

rule "consumo promedio"
     when
	$h : Habitacion(nombreHabitacion == "Otro" )
     then
	insert(new Valor($h,14,2.1));
end



//Una sola declaracion
//En vez de tener que declarar por cada tipo de sensor
//declare Sensor
	//nombre: String @key
	//Que HVAC/Climatiazacion analiza
	//tipoClimatizacion: TipoHVAC @key
	//Teoricamente sensores siempre encendidos...
	//Pero puede haber algun caso inesperado
	//encendido: boolean @key
	//presenciaDetectada: boolean @key
//end

//Cambio sensor por persona
//horas\precencia de 0 a 24

declare Presencia
  persona: Persona @key
  habitacion: Habitacion @key
end


declare Persona
	nombre: String @key
	presencia: boolean @key
	quiereEncender: boolean @key
	//presenciaInicio: int @key
	//presenciaFin: int @key
end

declare FuenteGasto
	//nombre: String @key
	encendidoTotal: boolean @key
	encendidoParcial: boolean @key
	tipoHvac: TipoHVAC @key
end

declare TipoHVAC
	HVAC: String @key
end

declare FuenteNatural
	//Aportacion puede ser luz, calefaccion, otro
	hvac: TipoHVAC @key
	//nombre: String @key
	presenciaTotal: boolean @key
	presenciaParcial: boolean @key
	//horaInicio: int @key
	//horaFin: int @key

end

//Momentos en que las dos aportaciones existen
declare NaturalArtificial
	hvac: TipoHVAC @key
	mayorUmbral: boolean @key
end

//Tsp=set point temperature, trec=recovery time
//Iluminacion como electricidad
rule "Carga hechos"
	then
		TipoHVAC ac = new TipoHVAC("AC");
		insert(ac);
		TipoHVAC calef = new TipoHVAC("Calefacción");
		insert(calef);
		TipoHVAC ilum = new TipoHVAC("Iluminación");
		insert(ilum);

		//Por el momento dejar uno de cada clase
		//insert(new FuenteGastoEnergetico("ACuno",false,ac));
		//insert(new FuenteGastoEnergetico("Calentador",false,calef));
		//insert(new FuenteGastoEnergetico("Focos",false,ilum));
		insert(new FuenteGasto(false,false,ac));
		insert(new FuenteGasto(false,false,calef));
		insert(new FuenteGasto(false,false,ilum));

		insert(new Persona("Emilino",true,true));

		//insert(new FuenteNatural(ilum,"LuzNatural",true));
		//insert(new FuenteNatural(calef,"Sol",true));
		//insert(new FuenteNatural(ac,"Ventana abierta",true));
		insert(new FuenteNatural(ilum,true,false));
		insert(new FuenteNatural(calef,true,false));
		insert(new FuenteNatural(ac,true,false));

		insert(new NaturalArtificial(ilum,false));
end

rule "Encender luces"
	when
		$persona: Persona(quiereEncender == true)
		$fuenteIlum: FuenteGasto(encendidoTotal==false && tipoHvac.getHVAC() =="Iluminacion")
	then
		$fuenteIlum.setEncendidoTotal(true);
end

rule "Hay luz de dia suficiente"
	when
		$ilum: FuenteNatural(hvac=="Iluminacion" && presenciaTotal==true)
		$fuenteIlum: FuenteGasto(encendidoTotal==true && tipoHvac.getHVAC() =="Iluminacion")
	then
		$fuenteIlum.setEncendidoTotal(false);
		$fuenteIlum.setEncendidoParcial(false);
end
rule "No hay luz de dia suficiente"
	when
		$ilum: FuenteNatural(hvac=="Iluminacion" && presenciaTotal==false && presenciaParcial==true)
		$fuenteIlum: FuenteGasto(encendidoTotal==true && tipoHvac.getHVAC() =="Iluminacion")
	then
		$fuenteIlum.setEncendidoTotal(false);
		$fuenteIlum.setEncendidoParcial(true);
end

rule "No hay luz de dia"
	when
		$ilum: FuenteNatural(hvac.getHVAC()=="Iluminacion" &&presenciaTotal==false &&presenciaParcial==false)
		$fuenteIlum: FuenteGasto(tipoHvac.getHVAC() =="Iluminacion")
	then
		$fuenteIlum.setEncendidoParcial(false);
		$fuenteIlum.setEncendidoTotal(true);
end

rule "Luz natural y artificial superan el umbral"
	when
		$ilum: FuenteNatural(hvac.getHVAC()=="Iluminacion" && (presenciaTotal==true || presenciaParcial==true))
		$fuenteIlum: FuenteGasto(tipoHvac.getHVAC() =="Iluminacion"&&(encendidoTotal==true||encendidoParcial==true))
		$juntos: NaturalArtificial(hvac.getHVAC() =="Iluminacion")
	then
		$juntos.setMayorUmbral(true);
		$fuenteIlum.setEncendidoTotal(false);
		$fuenteIlum.setEncendidoParcial(true);
end

rule "Luz natural y artificial no superan el umbral"
	when
		$ilum: FuenteNatural(hvac.getHVAC() =="Iluminacion" && presenciaTotal==false && presenciaParcial==false)
		$fuenteIlum: FuenteGasto(tipoHvac.getHVAC() =="Iluminacion"&&(encendidoTotal==true||encendidoParcial==true))
		$juntos: NaturalArtificial(hvac.getHVAC() =="Iluminacion")
	then
		$juntos.setMayorUmbral(false);
		$fuenteIlum.setEncendidoTotal(true);
		$fuenteIlum.setEncendidoParcial(false);
end

rule "Persona No Apagar luces"
	when
		$pers: Persona(presencia==true && quiereEncender==true)
		$fuenteIlum: FuenteGasto(tipoHvac.getHVAC() =="Iluminacion"&&(encendidoTotal==true||encendidoParcial==true))
	then
		$fuenteIlum.setEncendidoTotal(true);
		$fuenteIlum.setEncendidoParcial(false);
end

rule "Persona Apagar luces"
	when
		$pers: Persona(presencia==true && quiereEncender==false)
		$fuenteIlum: FuenteGasto(tipoHvac.getHVAC() =="Iluminacion"&&(encendidoTotal==true||encendidoParcial==true))
	then
		$fuenteIlum.setEncendidoTotal(false);
		$fuenteIlum.setEncendidoParcial(false);
end

rule "Apagar luces No hay nadie"
	when
		$pers: Persona(presencia==false)
		$fuenteIlum: FuenteGasto(tipoHvac.getHVAC() =="Iluminacion"&&(encendidoTotal==true||encendidoParcial==true))
	then
		$fuenteIlum.setEncendidoTotal(false);
		$fuenteIlum.setEncendidoParcial(false);
end

//AC es aire acondicionado
rule "Apagar aire cuando no hay nadie"
	when
		$pers: Persona(presencia==false)
		$aireAcondicionado: FuenteGasto(tipoHvac.getHVAC() == "Calefacción")
	then
		$aireAcondicionado.setEncendidoTotal(false);
		$aireAcondicionado.setEncendidoParcial(false);
end

rule "Activar aire cuando hay personas y no ventana"
	when
		$pers: Persona(presencia==true)
		$aireAcondicionado: FuenteGasto(tipoHvac.getHVAC() == "Calefacción")
		$ventana: FuenteNatural(hvac.getHVAC() == "Calefacción" && presenciaTotal == false)
	then
		$aireAcondicionado.setEncendidoTotal(true);
		$aireAcondicionado.setEncendidoParcial(false);
end

rule "Activar aire cuando hay personas y hay ventana"
	when
		$pers: Persona(presencia==true)
		$aireAcondicionado: FuenteGasto(tipoHvac.getHVAC() == "Calefacción")
		$ventana: FuenteNatural(hvac.getHVAC() == "Calefacción" && presenciaTotal == true)
	then
		$aireAcondicionado.setEncendidoTotal(false);
		$aireAcondicionado.setEncendidoParcial(true);
end